name: flutter_stetho_null_safety
description: Android上使用Chrome开发工具的Flutter网络检查器
version: 1.0.2
homepage: https://github.com/mdddj/flutter_stetho

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.brianegan.flutterstetho
        pluginClass: FlutterStethoPlugin

